on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  pipeline:
    uses: theSamsCo/.github/.github/workflows/pipeline.yaml@v1
    with:
      env: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      app_name: teste
